apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-etc-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 16Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/redis/etc/redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/redis/data
