apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: redis-data-pv
  resources:
    requests:
      storage: 2Gi
