apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: REDIS
  type: NodePort
  ports:
    - name: redis-server-port
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30379
