apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf-cm
data:
  redis-conf: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    bind 0.0.0.0
    protected-mode no
    port 6379
    timeout 0
    tcp-keepalive 300
    daemonize no
    loglevel debug
    logfile ""
    databases 16
    dir /data
